language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cppcheck
      - cmake
      - gcc-4.8

before_install:
  # install dependencies on osx
  #- if [ "$TRAVIS_OS_NAME" = "osx" ]; git clone https://github.com/sstephenson/bats.git; fi
  #- if [ "$TRAVIS_OS_NAME" = "osx" ]; ./bats/install.sh /usr/local; fi
  # install dependencies on linux
  #- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:duggan/bats --yes; fi
  #- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
  #- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq bats; fi

script:
  - cmake CMakeLists.txt && make
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cppcheck --enable=all ./src; fi

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./bin/linux/ttt ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./bin/mac/ttt ; fi
  #- if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./test.sh; fi
